spring:
  security:
    user:
      name: dongxin
      password: dx369*
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://dongxin:dx369*@localhost:8761/eureka/