spring:
  security:
    user:
      name: dongxin
      password: dx369*
  application:
    name: micro-service-gateway-zuul-reg-exp
server:
  port: 8889
eureka:
  client:
    serviceUrl:
      defaultZone: http://dongxin:dx369*@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    appname: micro-service-gateway-zuul-reg-exp


ribbon:
  eureka:
    enabled: true
